name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
            cd GoulartBot/
            git config --global --add safe.directory ~/GoulartBot
            sudo chown -R $USER:$USER .git
            sudo -i -u root bash << 'EOC'
              export PATH=$PATH:/usr/local/bin
              git pull origin main
              npm install
              pm2 delete 0
              pm2 start src/index.js
            EOC
          EOF
